---

#passenger repository setup.
- name: Add Passenger apt key.
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 561F9B9CAC40B2F7
    state: present

- name: Add apt HTTPS capabilities.
  apt: name=apt-transport-https state=present

- name: Add Phusion apt repo.
  apt_repository:
    repo: 'deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ansible_distribution_release}} main'
    state: present
    update_cache: yes

# Nginx and passenger installation.
- name: Install Nginx and Passenger.
  apt: "pkg={{ item }} state=installed"
  with_items:
   - nginx-extras
   - passenger
  become: yes

# Nginx and passenger configuration.
- name: Copy Nginx configuration into place.
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Copy default nginx site configuration file
  copy:
    src: default
    dest: /etc/nginx/sites-available/default
  notify: restart nginx

